ldap_domain: srvmediaschool.local
ldap_admin_password: "123456789"
ldap_base_dn: "dc=srvmediaschool,dc=local"
ldap_organization: "Media School"

ldap_tls_enable: false
ldap_tls_cert_file: "/etc/ssl/certs/ldap.crt"
ldap_tls_key_file: "/etc/ssl/private/ldap.key"
ldap_tls_ca_file: "/etc/ssl/certs/ca.pem"

ldap_host: "10.0.2.15"