# --- CLAMAV (variables pour docker-compose) ---
clamav_image: "clamav/clamav:1.4_base"
clamav_clamd_port: 3310
clamav_db_volume_name: "clamav_db"
clamav_run_unprivileged: false

# --- WIREGUARD ---
wg_easy_data_dir: "/home/iris/sisr/securite/wg-easy"
wg_easy_host: "37.64.159.66"
wg_easy_password: "wireguard123!"
